global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # 监控Spring Boot应用
  - job_name: 'travel-server'
    static_configs:
      - targets: ['travel-server:8070']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s
    
  # 监控MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    scrape_interval: 30s
    
  # 监控Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    
  # 监控Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s


















